-- CYBERSTAT FINAL BOSQICHI — centralized voting schema
create extension if not exists pgcrypto;

create table if not exists public.candidates (
  id text primary key,
  name text not null,
  bio text not null default '',
  active boolean not null default true,
  image_url text,
  rating numeric(2,1) not null default 5.0 check (rating >= 0 and rating <= 5),
  votes integer not null default 0 check (votes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.candidates add column if not exists rating numeric(2,1) not null default 5.0;
alter table public.candidates add column if not exists image_url text;
alter table public.candidates add column if not exists project_logo_url text;
alter table public.candidates add column if not exists author_name text not null default '';
alter table public.candidates add column if not exists votes integer not null default 0;

create table if not exists public.survey_settings (
  id integer primary key default 1 check (id = 1),
  project_name text not null default 'CYBERSTAT',
  tagline text not null default 'CYBERSTAT FINAL BOSQICHI',
  status text not null default 'FAOL' check (status in ('FAOL','TOXTATILGAN','YAKUNLANGAN')),
  results_visible boolean not null default true,
  countdown_end timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.survey_settings add column if not exists countdown_end timestamptz;

create table if not exists public.survey_stats (
  id integer primary key default 1 check (id = 1),
  participants integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  candidate_id text not null references public.candidates(id),
  voter_id uuid not null,
  created_at timestamptz not null default now()
);
create unique index if not exists votes_one_per_voter on public.votes(voter_id);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor text not null default 'ADMIN',
  action text not null,
  target text,
  detail text,
  created_at timestamptz not null default now()
);

insert into public.survey_settings(id) values(1) on conflict(id) do nothing;
insert into public.survey_stats(id) values(1) on conflict(id) do nothing;

-- Remove the old public table permissions. Admin mutations happen only through RPC.
alter table public.candidates enable row level security;
alter table public.survey_settings enable row level security;
alter table public.survey_stats enable row level security;
alter table public.votes enable row level security;
alter table public.audit_logs enable row level security;

revoke all on public.candidates from anon, authenticated;
revoke all on public.survey_settings from anon, authenticated;
revoke all on public.survey_stats from anon, authenticated;
revoke all on public.votes from anon, authenticated;
revoke all on public.audit_logs from anon, authenticated;

-- Public read is intentionally exposed through RPCs, so private audit/admin data never reaches clients.

drop function if exists public.is_admin();
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false);
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create or replace function public.get_public_state()
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_candidates jsonb;
  v_settings jsonb;
  v_participants integer;
begin
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', id, 'name', name, 'bio', bio, 'active', active,
    'image_url', image_url, 'project_logo_url', project_logo_url, 'author_name', author_name, 'rating', rating, 'votes', votes
  ) order by votes desc, created_at asc), '[]'::jsonb)
  into v_candidates from public.candidates where active = true;
  select to_jsonb(s) - 'id' into v_settings from public.survey_settings s where id=1;
  select participants into v_participants from public.survey_stats where id=1;
  return jsonb_build_object('candidates',v_candidates,'settings',coalesce(v_settings,'{}'::jsonb),'participants',coalesce(v_participants,0));
end;
$$;
revoke all on function public.get_public_state() from public;
grant execute on function public.get_public_state() to anon, authenticated;

create or replace function public.cast_vote(p_candidate_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_user uuid := auth.uid(); v_votes integer; v_participants integer; v_status text;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  select status into v_status from public.survey_settings where id=1;
  if v_status <> 'FAOL' then raise exception 'VOTING_NOT_ACTIVE'; end if;
  if exists(select 1 from public.votes where voter_id=v_user) then raise exception 'ALREADY_VOTED'; end if;
  perform 1 from public.candidates where id=p_candidate_id and active=true for update;
  if not found then raise exception 'CANDIDATE_NOT_FOUND'; end if;
  insert into public.votes(candidate_id,voter_id) values(p_candidate_id,v_user);
  update public.candidates set votes=votes+1, updated_at=now() where id=p_candidate_id returning votes into v_votes;
  update public.survey_stats set participants=participants+1, updated_at=now() where id=1 returning participants into v_participants;
  return jsonb_build_object('ok',true,'candidate_id',p_candidate_id,'votes',v_votes,'participants',v_participants);
exception when unique_violation then raise exception 'ALREADY_VOTED';
end;
$$;
revoke all on function public.cast_vote(text) from public;
grant execute on function public.cast_vote(text) to anon, authenticated;

drop function if exists public.admin_save_candidate(text,text,text,boolean,text,numeric);
create or replace function public.admin_save_candidate(
  p_id text, p_name text, p_bio text default '', p_active boolean default true,
  p_image_url text default null, p_rating numeric default 5.0,
  p_author_name text default '', p_project_logo_url text default null
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_id text; v_old text;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if length(trim(coalesce(p_name,''))) < 2 or length(trim(coalesce(p_name,''))) > 120 then raise exception 'INVALID_NAME'; end if;
  if p_rating < 0 or p_rating > 5 then raise exception 'INVALID_RATING'; end if;
  v_id := nullif(trim(coalesce(p_id,'')),'');
  if v_id is null then
    v_id := 'c_' || replace(gen_random_uuid()::text,'-','');
    insert into public.candidates(id,name,bio,active,image_url,rating,author_name,project_logo_url)
    values(v_id,trim(p_name),trim(coalesce(p_bio,'')),coalesce(p_active,true),p_image_url,round(p_rating::numeric,1),trim(coalesce(p_author_name,'')),p_project_logo_url);
    insert into public.audit_logs(actor,action,target,detail) values('ADMIN','NOMZOD_QOSHILDI',trim(p_name),'Yangi finalist yaratildi. ID: '||v_id);
  else
    select name into v_old from public.candidates where id=v_id;
    if v_old is null then raise exception 'CANDIDATE_NOT_FOUND'; end if;
    update public.candidates set name=trim(p_name),bio=trim(coalesce(p_bio,'')),active=coalesce(p_active,true),image_url=p_image_url,rating=round(p_rating::numeric,1),author_name=trim(coalesce(p_author_name,'')),project_logo_url=p_project_logo_url,updated_at=now() where id=v_id;
    insert into public.audit_logs(actor,action,target,detail) values('ADMIN','NOMZOD_YANGILANDI',trim(p_name),'Oldingi nom: '||v_old||'. ID: '||v_id);
  end if;
  return jsonb_build_object('ok',true,'id',v_id);
end;
$$;
revoke all on function public.admin_save_candidate(text,text,text,boolean,text,numeric,text,text) from public;
grant execute on function public.admin_save_candidate(text,text,text,boolean,text,numeric,text,text) to authenticated;

create or replace function public.admin_delete_candidate(p_candidate_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_name text; v_votes integer;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select name,votes into v_name,v_votes from public.candidates where id=p_candidate_id for update;
  if v_name is null then raise exception 'CANDIDATE_NOT_FOUND'; end if;
  if v_votes > 0 then
    update public.candidates set active=false,updated_at=now() where id=p_candidate_id;
    insert into public.audit_logs(actor,action,target,detail) values('ADMIN','NOMZOD_ARXIVLANDI',v_name,'Ovoz mavjudligi sababli o‘chirilmadi, faolsizlantirildi.');
  else
    delete from public.candidates where id=p_candidate_id;
    insert into public.audit_logs(actor,action,target,detail) values('ADMIN','NOMZOD_OCHIRILDI',v_name,'Nomzod va uning ovozlari 0 bo‘lgan holatda o‘chirildi.');
  end if;
  return jsonb_build_object('ok',true);
end;
$$;
revoke all on function public.admin_delete_candidate(text) from public;
grant execute on function public.admin_delete_candidate(text) to authenticated;

create or replace function public.admin_adjust_votes(p_candidate_id text,p_delta integer,p_reason text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_name text; v_votes integer; v_new integer; v_participants integer;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if p_delta = 0 then raise exception 'DELTA_REQUIRED'; end if;
  if length(trim(coalesce(p_reason,''))) < 3 then raise exception 'REASON_REQUIRED'; end if;
  select name,votes into v_name,v_votes from public.candidates where id=p_candidate_id for update;
  if v_name is null then raise exception 'CANDIDATE_NOT_FOUND'; end if;
  v_new := v_votes + p_delta;
  if v_new < 0 then raise exception 'NEGATIVE_VOTES'; end if;
  update public.candidates set votes=v_new,updated_at=now() where id=p_candidate_id;
  if p_delta > 0 then
    update public.survey_stats set participants=participants+p_delta,updated_at=now() where id=1 returning participants into v_participants;
  else
    update public.survey_stats set participants=greatest(0,participants+p_delta),updated_at=now() where id=1 returning participants into v_participants;
  end if;
  insert into public.audit_logs(actor,action,target,detail) values('ADMIN',case when p_delta>0 then 'OVOZ_QOSHILDI' else 'OVOZ_AYIRILDI' end,v_name,'Miqdor: '||p_delta||'. Sabab: '||trim(p_reason));
  return jsonb_build_object('ok',true,'votes',v_new,'participants',v_participants);
end;
$$;
revoke all on function public.admin_adjust_votes(text,integer,text) from public;
grant execute on function public.admin_adjust_votes(text,integer,text) to authenticated;

create or replace function public.admin_set_settings(p_status text,p_results_visible boolean,p_countdown_end timestamptz)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if p_status not in ('FAOL','TOXTATILGAN','YAKUNLANGAN') then raise exception 'INVALID_STATUS'; end if;
  update public.survey_settings set status=p_status,results_visible=coalesce(p_results_visible,true),countdown_end=p_countdown_end,updated_at=now() where id=1;
  insert into public.audit_logs(actor,action,target,detail) values('ADMIN','TIZIM_HOLATI',p_status,'Ovoz berish holati yoki natija ko‘rinishi o‘zgartirildi.');
  return jsonb_build_object('ok',true);
end;
$$;
revoke all on function public.admin_set_settings(text,boolean,timestamptz) from public;
grant execute on function public.admin_set_settings(text,boolean,timestamptz) to authenticated;

create or replace function public.admin_get_state()
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_candidates jsonb; v_settings jsonb; v_participants integer; v_logs jsonb;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select coalesce(jsonb_agg(to_jsonb(c) order by c.votes desc,c.created_at asc),'[]'::jsonb) into v_candidates from public.candidates c;
  select to_jsonb(s) into v_settings from public.survey_settings s where id=1;
  select participants into v_participants from public.survey_stats where id=1;
  select coalesce(jsonb_agg(to_jsonb(l) order by l.created_at desc),'[]'::jsonb) into v_logs from (select * from public.audit_logs order by created_at desc limit 100) l;
  return jsonb_build_object('candidates',v_candidates,'settings',v_settings,'participants',coalesce(v_participants,0),'logs',v_logs);
end;
$$;
revoke all on function public.admin_get_state() from public;
grant execute on function public.admin_get_state() to authenticated;

-- Realtime is enabled only for public-safe tables. Admin audit logs remain private.
do $$ begin alter publication supabase_realtime add table public.candidates; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.survey_settings; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.survey_stats; exception when duplicate_object then null; end $$;

-- Candidate image storage: create a PUBLIC bucket named candidate-images in Supabase Storage,
-- then apply this policy. Public read is intentional; uploads remain admin-only.
drop policy if exists "admins upload candidate images" on storage.objects;
create policy "admins upload candidate images" on storage.objects
for insert to authenticated
with check (bucket_id='candidate-images' and public.is_admin());
