"use client";
import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,ArrowDown,ArrowRight,ArrowUp,BarChart3,Check,Clock3,Edit3,Eye,EyeOff,ImagePlus,LogOut,Plus,RefreshCw,ShieldCheck,Trophy,Trash2,Users,Vote,X,Zap} from 'lucide-react';
import {supabase} from '../lib/supabase';

const FALLBACK={project_name:'CYBERSTAT',tagline:'CYBERSTAT FINAL BOSQICHI',status:'FAOL',results_visible:true,countdown_end:null};
const fmt=n=>new Intl.NumberFormat('uz-UZ').format(Number(n||0));
const pct=(v,t)=>t?Number(v||0)/t*100:0;
const errText=e=>String(e?.message||e||'Noma’lum server xatosi').replace(/^.*?: /,'');

async function voterSession(){const {data,error}=await supabase.auth.getSession();if(error)throw error;if(data?.session?.user)return data.session;const r=await supabase.auth.signInAnonymously();if(r.error)throw r.error;if(!r.data?.session?.user)throw new Error('ANONYMOUS_AUTH_FAILED');return r.data.session;}
async function publicState(){const {data,error}=await supabase.rpc('get_public_state');if(error)throw error;return data||{candidates:[],settings:FALLBACK,participants:0};}
async function adminState(){const {data,error}=await supabase.rpc('admin_get_state');if(error)throw error;return data;}

export default function CyberStatApp(){
 const [mode,setMode]=useState(typeof window!=='undefined'&&window.location.pathname.startsWith('/admin')?'admin':'public');
  return mode==='admin' ? <AdminApp onPublic={()=>{history.pushState({},'', '/');setMode('public')}}/> : <PublicApp onAdmin={()=>{history.pushState({},'', '/admin');setMode('admin')}}/>;
}

function PublicApp({onAdmin}){
 const [data,setData]=useState({candidates:[],settings:FALLBACK,participants:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[voted,setVoted]=useState(false),[notice,setNotice]=useState(''),[syncAt,setSyncAt]=useState(null);
 const sync=useCallback(async()=>{try{const d=await publicState();setData(d);setSyncAt(new Date());setError('')}catch(e){console.error(e);setError(errText(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{sync();const ch=supabase.channel('cyberstat-public-live').on('postgres_changes',{event:'*',schema:'public',table:'candidates'},sync).on('postgres_changes',{event:'*',schema:'public',table:'survey_settings'},sync).on('postgres_changes',{event:'*',schema:'public',table:'survey_stats'},sync).subscribe();return()=>supabase.removeChannel(ch)},[sync]);
 const total=useMemo(()=>data.candidates.reduce((a,c)=>a+Number(c.votes||0),0),[data.candidates]);
 const vote=async()=>{if(!selected||voted||data.settings.status!=='FAOL')return;try{await voterSession();const {data:r,error:e}=await supabase.rpc('cast_vote',{p_candidate_id:selected.id});if(e)throw e;if(!r?.ok)throw new Error('VOTE_NOT_CONFIRMED');setVoted(true);setSelected(null);setNotice('Ovozingiz muvaffaqiyatli qayd etildi.');await sync()}catch(e){setNotice(String(e?.message||'Ovoz qabul qilinmadi.').includes('ALREADY_VOTED')?'Siz avval ovoz bergansiz.':'Ovoz qabul qilinmadi: '+errText(e))}};
 if(loading)return <Loading/>;
 const closed=data.settings.status==='YAKUNLANGAN';
 return <div className="app"><CyberBg/><header className="nav"><div className="logo"><span><ShieldCheck/></span><b>CYBERSTAT</b><small>FINAL ARENA</small></div><div className="nav-live"><i/> LIVE ARENA</div><nav><a href="#arena">ARENA</a><a href="#finalists">FINALISTLAR</a><a href="#ranking">REYTING</a></nav><button className="nav-btn" onClick={()=>document.getElementById('finalists')?.scrollIntoView({behavior:'smooth'})}><Vote/> OVOZ BERISH</button></header>
 {error&&<div className="alert error"><span>{error}</span><button onClick={sync}><RefreshCw/> QAYTA URINISH</button></div>}{notice&&<div className="alert success"><Check/><span>{notice}</span><button onClick={()=>setNotice('')}><X/></button></div>}
 <main>
 <section id="arena" className="arena"><div className="arena-copy"><div className="kicker"><span>● FINAL EVENT</span><em>{closed?'FINAL YAKUNLANDI':'LIVE VOTING'}</em></div><h1>CYBERSTAT<br/><strong>FINAL BOSQICHI</strong></h1><p>Yakuniy bosqichda o‘zingiz munosib deb bilgan finalistga ovoz bering.</p><div className="hero-actions"><button className="primary" disabled={data.settings.status!=='FAOL'} onClick={()=>document.getElementById('finalists')?.scrollIntoView({behavior:'smooth'})}><Zap/> {closed?'FINAL YAKUNLANGAN':'OVOZ BERISH'} <ArrowRight/></button><span className="sync-label"><i/> SERVER {syncAt?'SINXRON': 'ULANISH'}</span></div></div><ArenaPanel candidates={data.candidates} total={total} settings={data.settings}/></section>
 <section className="metrics"><Metric label="JAMI OVOZ" value={total}/><Metric label="ISHTIROKCHI" value={data.participants}/><Metric label="FINALIST" value={data.candidates.length}/><Metric label="HOLAT" value={closed?'CLOSED':'LIVE'}/></section>
 <section id="finalists" className="section"><SectionHead eyebrow="FINALISTS / 05" title="Finalistlar" text="Har bir finalistning loyiha ma’lumotlari, reytingi va joriy ovozlari."/><div className="cards">{data.candidates.map((c,i)=><Candidate key={c.id} c={c} rank={i+1} total={total} disabled={voted||data.settings.status!=='FAOL'} select={()=>setSelected(c)}/>)}</div></section>
 <section id="ranking" className="ranking section"><SectionHead eyebrow="LIVE RANKING" title="Jonli reyting" text="Ovozlar markaziy serverdan real vaqt rejimida yangilanadi."/><div className="rank-list">{data.candidates.map((c,i)=><RankRow key={c.id} c={c} rank={i+1} total={total}/>)}</div></section>
 {closed&&<Podium candidates={data.candidates}/>}<div className="public-note">Faqat finalist nomi, loyiha ma’lumoti, reytingi, ovozlar soni va reytingdagi o‘rni ommaga ko‘rsatiladi.</div>
 </main><footer><span>CYBERSTAT FINAL ARENA</span><span>SECURE • CENTRAL • REAL-TIME</span><button className="admin-link" onClick={onAdmin}>ADMIN</button></footer>{selected&&<Confirm c={selected} onClose={()=>setSelected(null)} onConfirm={vote}/>}</div>;
}

function ArenaPanel({candidates,total,settings}){const leader=candidates[0], end=settings.countdown_end?new Date(settings.countdown_end):null;return <div className="arena-panel"><div className="panel-top"><span><i/> LIVE ARENA</span><Countdown end={end} closed={settings.status==='YAKUNLANGAN'}/></div><div className="radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-core"><Trophy/><b>{leader?'#01':'—'}</b><small>LEADER</small></div></div>{leader?<div className="panel-leader"><small>HOZIRGI YETAKCHI</small><strong>{leader.name}</strong><span>{fmt(leader.votes)} OVOZ • {pct(leader.votes,total).toFixed(1)}%</span></div>:<div className="empty">Finalistlar hali kiritilmagan.</div>}</div>}
function Countdown({end,closed}){const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);if(closed)return <b className="closed-tag">CLOSED</b>;if(!end)return <b className="countdown">FINAL LIVE</b>;const s=Math.max(0,Math.floor((end-now)/1000));const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;return <b className="countdown"><Clock3/> {d?`${d}K `:''}{String(h).padStart(2,'0')}:{String(m).padStart(2,'0')}:{String(sec).padStart(2,'0')}</b>}
function Candidate({c,rank,total,disabled,select}){return <article className="candidate"><div className="photo">{c.image_url?<img src={c.image_url} alt={c.author_name||c.name}/>:<div><ShieldCheck/></div>}<span>#{String(rank).padStart(2,'0')}</span><div className="author-chip"><small>LOYIHA MUALLIFI</small><strong>{c.author_name||'Muallif'}</strong></div></div><div className="cbody"><div className="project-head">{c.project_logo_url?<img className="project-logo" src={c.project_logo_url} alt="Loyiha logosi"/>:<div className="project-logo placeholder"><ShieldCheck/></div>}<div><div className="cmeta"><span>FINALIST / LOYIHA</span><b>★ {Number(c.rating||0).toFixed(1)}/5.0</b></div><h3>{c.name}</h3></div></div><p className="project-desc">{c.bio||'Loyiha haqida ma’lumot kiritilmagan.'}</p><div className="vote-line"><strong>{fmt(c.votes)}</strong><span>OVOZ</span><em>{pct(c.votes,total).toFixed(1)}%</em></div><div className="bar"><i style={{width:`${Math.min(100,pct(c.votes,total))}%`}}/></div><button onClick={select} disabled={disabled}><Vote/> OVOZ BERISH <ArrowRight/></button></div></article>}
function RankRow({c,rank,total}){return <div className="rank-row"><b className="rank-no">{String(rank).padStart(2,'0')}</b>{c.image_url?<img src={c.image_url} alt=""/>:<span className="rank-avatar"><ShieldCheck/></span>}<div><strong>{c.name}</strong><small>★ {Number(c.rating||0).toFixed(1)} / 5.0</small></div><div className="rank-progress"><i style={{width:`${Math.min(100,pct(c.votes,total))}%`}}/></div><b className="rank-votes">{fmt(c.votes)} <small>OVOZ</small></b></div>}
function Podium({candidates}){return <section className="podium section"><div className="kicker"><span>FINAL RESULT</span><em>OFFICIAL</em></div><h2>Final natijasi</h2><div className="podium-grid">{candidates.slice(0,3).map((c,i)=><div className={`pod p${i+1}`} key={c.id}><span>#{i+1}</span><Trophy/><strong>{c.name}</strong><b>{fmt(c.votes)} ovoz</b></div>)}</div></section>}
function Confirm({c,onClose,onConfirm}){return <div className="modal-bg"><div className="modal"><button onClick={onClose}><X/></button><small>SECURE BALLOT</small><h2>{c.name}</h2><div className="confirm-rating">★ {Number(c.rating||0).toFixed(1)} / 5.0</div><p>Bu finalistga bitta ovoz berishni tasdiqlaysiz. Ovoz serverda qayd etiladi.</p><div><button className="secondary" onClick={onClose}>BEKOR</button><button className="primary" onClick={onConfirm}><Check/> TASDIQLASH</button></div></div></div>}
function Metric({label,value}){return <div><small>{label}</small><b>{typeof value==='number'?fmt(value):value}</b></div>};function SectionHead({eyebrow,title,text}){return <div className="section-head"><div><small>{eyebrow}</small><h2>{title}</h2><p>{text}</p></div></div>};function Loading(){return <div className="loading"><ShieldCheck/><b>CYBERSTAT</b><span>FINAL ARENA INITIALIZING…</span></div>};function CyberBg(){return <div className="bg"><div className="grid"/><div className="glow g1"/><div className="glow g2"/></div>}

function AdminApp({onPublic}){
 const [session,setSession]=useState(null),[login,setLogin]=useState({email:'',password:''}),[state,setState]=useState(null),[tab,setTab]=useState('dashboard'),[edit,setEdit]=useState(null),[adjust,setAdjust]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=useCallback(async()=>{try{setState(await adminState())}catch(e){setMsg(errText(e))}},[]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session))},[]);
 useEffect(()=>{if(session)load()},[session,load]);
 async function signIn(e){e.preventDefault();setBusy(true);setMsg('');const {data,error}=await supabase.auth.signInWithPassword(login);setBusy(false);if(error)setMsg(errText(error));else setSession(data.session)}
 if(!session)return <div className="admin-login"><CyberBg/><div className="login-card"><span className="admin-mark"><ShieldCheck/></span><small>CYBERSTAT / CONTROL CENTER</small><h1>Admin panel</h1><p>Markaziy boshqaruv tizimiga kirish.</p><form onSubmit={signIn}><input type="email" placeholder="Email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input type="password" placeholder="Parol" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="primary" disabled={busy}>{busy?'KIRILMOQDA…':'KIRISH'} <ArrowRight/></button></form>{msg&&<div className="form-error">{msg}</div>}<button className="back-public" onClick={onPublic}>← Public sahifaga qaytish</button></div></div>;
 const cands=state?.candidates||[],settings=state?.settings||FALLBACK,total=cands.reduce((a,c)=>a+Number(c.votes||0),0);
 async function saveCandidate(c){setBusy(true);try{const upload=async(file,prefix,existing)=>{if(!file)return existing||null;if(file.size>5*1024*1024)throw new Error('Rasm 5 MB dan oshmasin.');const ext=file.name.split('.').pop().toLowerCase();if(!['png','jpg','jpeg','webp'].includes(ext))throw new Error('Faqat PNG/JPG/WEBP.');const path=`${prefix}/${c.id||crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from('candidate-images').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(up.error)throw up.error;return supabase.storage.from('candidate-images').getPublicUrl(path).data.publicUrl};const image=await upload(c.author_file,'authors',c.image_url);const logo=await upload(c.logo_file,'logos',c.project_logo_url);const r=await supabase.rpc('admin_save_candidate',{p_id:c.id||null,p_name:c.name,p_bio:c.bio||'',p_active:!!c.active,p_image_url:image,p_rating:Number(c.rating||5),p_author_name:c.author_name||'',p_project_logo_url:logo});if(r.error)throw r.error;setEdit(null);setMsg('Finalist, muallif rasmi va loyiha logosi serverga saqlandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
 async function adjustVotes(){setBusy(true);try{const r=await supabase.rpc('admin_adjust_votes',{p_candidate_id:adjust.id,p_delta:Number(adjust.delta),p_reason:adjust.reason});if(r.error)throw r.error;setAdjust(null);setMsg('Ovozlar markaziy serverda yangilandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
 async function setSettings(){setBusy(true);try{const r=await supabase.rpc('admin_set_settings',{p_status:settings.status,p_results_visible:settings.results_visible,p_countdown_end:settings.countdown_end||null});if(r.error)throw r.error;setMsg('Final holati yangilandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
 async function remove(id){if(!confirm('Nomzodni o‘chirish/faolsizlantirishni tasdiqlaysizmi?'))return;setBusy(true);const r=await supabase.rpc('admin_delete_candidate',{p_id:id});setBusy(false);if(r.error)setMsg(errText(r.error));else{setMsg('Nomzod holati yangilandi.');load()}}
 async function logout(){await supabase.auth.signOut();setSession(null);onPublic()}
 return <div className="admin-shell"><CyberBg/><header className="admin-top"><div className="logo"><span><ShieldCheck/></span><b>CYBERSTAT</b><small>CONTROL CENTER</small></div><div className="admin-actions"><button onClick={onPublic}><Eye/> PUBLIC</button><button onClick={logout}><LogOut/> CHIQISH</button></div></header><div className="admin-layout"><aside>{[['dashboard','Dashboard'],['candidates','Finalistlar'],['votes','Ovoz boshqaruvi'],['logs','Audit log'],['system','Final boshqaruvi']].map(([id,t])=><button key={id} className={tab===id?'sel':''} onClick={()=>setTab(id)}>{t}</button>)}</aside><main className="admin-main">{msg&&<div className="admin-msg">{msg}<button onClick={()=>setMsg('')}><X/></button></div>}{tab==='dashboard'&&<AdminDashboard cands={cands} total={total} participants={state?.participants||0} settings={settings}/>} {tab==='candidates'&&<AdminCandidates cands={cands} onEdit={setEdit} onNew={()=>setEdit({id:null,name:'',bio:'',author_name:'',active:true,rating:5,image_url:'',project_logo_url:'',author_file:null,logo_file:null})} onDelete={remove}/>} {tab==='votes'&&<AdminVotes cands={cands} onAdjust={setAdjust}/>} {tab==='logs'&&<AdminLogs logs={state?.logs||[]}/>} {tab==='system'&&<AdminSystem settings={settings} busy={busy} onSave={async draft=>{setState({...state,settings:draft});await (async()=>{setBusy(true);try{const r=await supabase.rpc('admin_set_settings',{p_status:draft.status,p_results_visible:draft.results_visible,p_countdown_end:draft.countdown_end||null});if(r.error)throw r.error;setMsg('Final holati yangilandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}})()}}/>}</main></div>{edit&&<CandidateEditor c={edit} setC={setEdit} onClose={()=>setEdit(null)} onSave={saveCandidate} busy={busy}/>} {adjust&&<AdjustModal a={adjust} setA={setAdjust} onClose={()=>setAdjust(null)} onSave={adjustVotes} busy={busy}/>}</div>
}
function AdminDashboard({cands,total,participants,settings}){return <div><AdminTitle eyebrow="COMMAND CENTER" title="Final arena dashboard" text="Markaziy ovozlar, finalistlar va final holati bir joyda."/><div className="dash-cards"><Metric label="JAMI OVOZ" value={total}/><Metric label="ISHTIROKCHI" value={participants}/><Metric label="FINALIST" value={cands.length}/><Metric label="STATUS" value={settings.status}/></div><div className="admin-panel"><h3>Jonli reyting</h3>{cands.map((c,i)=><RankRow key={c.id} c={c} rank={i+1} total={total}/>)}</div></div>}
function AdminCandidates({cands,onEdit,onNew,onDelete}){return <div><AdminTitle eyebrow="CANDIDATE MANAGEMENT" title="Finalistlar" text="Muallif rasmi, loyiha logosi, tavsif, reyting va faol holatni boshqaring."/><button className="primary add" onClick={onNew}><Plus/> YANGI FINALIST</button><div className="admin-table">{cands.map((c,i)=><div className="admin-candidate" key={c.id}>{c.image_url?<img src={c.image_url} alt=""/>:<span><ShieldCheck/></span>}<div><b>#{String(i+1).padStart(2,'0')} {c.name}</b><small>{c.author_name||'Muallif ko‘rsatilmagan'} • ★ {Number(c.rating||0).toFixed(1)} • {fmt(c.votes)} ovoz • {c.active?'FAOL':'YOPIQ'}</small></div>{c.project_logo_url&&<img className="admin-logo-thumb" src={c.project_logo_url} alt=""/>}<button onClick={()=>onEdit({...c,author_file:null,logo_file:null})}><Edit3/></button><button onClick={()=>onDelete(c.id)}><Trash2/></button></div>)}</div></div>}
function AdminVotes({cands,onAdjust}){return <div><AdminTitle eyebrow="VOTE CONTROL" title="Ovoz boshqaruvi" text="Qo‘shish yoki ayirish faqat server RPC orqali amalga oshadi va sabab auditga yoziladi."/><div className="admin-table">{cands.map(c=><div className="vote-admin-row" key={c.id}><div><b>{c.name}</b><small>{fmt(c.votes)} OVOZ</small></div><button className="plus" onClick={()=>onAdjust({id:c.id,name:c.name,delta:1,reason:''})}><ArrowUp/> QO‘SHISH</button><button className="minus" onClick={()=>onAdjust({id:c.id,name:c.name,delta:-1,reason:''})}><ArrowDown/> AYIRISH</button></div>)}</div></div>}
function AdminLogs({logs}){return <div><AdminTitle eyebrow="AUDIT TRAIL" title="O‘zgarishlar tarixi" text="Bu ma’lumotlar faqat administrator uchun ko‘rinadi."/><div className="logs">{logs.map(l=><div key={l.id}><span>{new Date(l.created_at).toLocaleString('uz-UZ')}</span><b>{l.action}</b><strong>{l.target||'—'}</strong><p>{l.detail||''}</p></div>)}</div></div>}
function AdminSystem({settings,busy,onSave}){const [draft,setDraft]=useState(settings);useEffect(()=>setDraft(settings),[settings]);return <div><AdminTitle eyebrow="FINAL CONTROL" title="Final boshqaruvi" text="Ovoz berishni oching, vaqtincha to‘xtating yoki finalni yakunlang."/><div className="system-panel"><label>Holat<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>FAOL</option><option>TOXTATILGAN</option><option>YAKUNLANGAN</option></select></label><label>Natijalarni ommaga ko‘rsatish<select value={draft.results_visible?'true':'false'} onChange={e=>setDraft({...draft,results_visible:e.target.value==='true'})}><option value="true">Ha</option><option value="false">Yo‘q</option></select></label><label>Countdown tugash vaqti<input type="datetime-local" value={draft.countdown_end?new Date(draft.countdown_end).toISOString().slice(0,16):''} onChange={e=>setDraft({...draft,countdown_end:e.target.value?new Date(e.target.value).toISOString():null})}/></label><button className="primary" disabled={busy} onClick={()=>onSave(draft)}>O‘ZGARISHLARNI SAQLASH</button></div></div>}
function AdminTitle({eyebrow,title,text}){return <div className="admin-title"><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>}
function CandidateEditor({c,setC,onClose,onSave,busy}){return <div className="modal-bg"><div className="modal editor"><button onClick={onClose}><X/></button><small>FINALIST CONFIG / MEDIA</small><h2>{c.id?'Finalistni tahrirlash':'Yangi finalist'}</h2><input placeholder="Loyiha nomi" value={c.name} onChange={e=>setC({...c,name:e.target.value})}/><input placeholder="Loyiha muallifi" value={c.author_name||''} onChange={e=>setC({...c,author_name:e.target.value})}/><textarea placeholder="Loyiha tavsifi" value={c.bio} onChange={e=>setC({...c,bio:e.target.value})}/><label>Reyting: {Number(c.rating||0).toFixed(1)} / 5.0<input type="range" min="0" max="5" step="0.1" value={c.rating||0} onChange={e=>setC({...c,rating:e.target.value})}/></label><div className="media-grid"><label className="file-box"><ImagePlus/><span>Muallif rasmi</span><small>{c.author_file?c.author_file.name:(c.image_url?'Mavjud rasmni saqlash':'Rasm tanlang')}</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setC({...c,author_file:e.target.files?.[0]||null})}/></label><label className="file-box"><ImagePlus/><span>Loyiha logosi</span><small>{c.logo_file?c.logo_file.name:(c.project_logo_url?'Mavjud logo saqlanadi':'Logo tanlang')}</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setC({...c,logo_file:e.target.files?.[0]||null})}/></label></div>{(c.author_file||c.image_url)&&<div className="editor-preview"><div>{c.author_file?<span>{c.author_file.name}</span>:<img src={c.image_url} alt=""/>}<small>MUALLIF</small></div>{(c.logo_file||c.project_logo_url)&&<div>{c.logo_file?<span>{c.logo_file.name}</span>:<img src={c.project_logo_url} alt=""/>}<small>LOGO</small></div>}</div>}<label className="switch"><input type="checkbox" checked={!!c.active} onChange={e=>setC({...c,active:e.target.checked})}/> FAOL</label><div><button className="secondary" onClick={onClose}>BEKOR</button><button className="primary" disabled={busy} onClick={()=>onSave(c)}><Check/> SAQLASH</button></div></div></div>}
function AdjustModal({a,setA,onClose,onSave,busy}){return <div className="modal-bg"><div className="modal"><button onClick={onClose}><X/></button><small>SECURE VOTE ADJUSTMENT</small><h2>{a.name}</h2><div className="adjust-grid"><button onClick={()=>setA({...a,delta:Number(a.delta||0)+1})}>+1</button><button onClick={()=>setA({...a,delta:Number(a.delta||0)-1})}>−1</button><input type="number" value={a.delta} onChange={e=>setA({...a,delta:e.target.value})}/></div><textarea placeholder="O‘zgarish sababi — majburiy" value={a.reason} onChange={e=>setA({...a,reason:e.target.value})}/><p className="warning">Sabab audit logga yoziladi. O‘zgarish public reytingga real vaqtda tarqaladi.</p><div><button className="secondary" onClick={onClose}>BEKOR</button><button className="primary" disabled={busy} onClick={onSave}><Check/> TASDIQLASH</button></div></div></div>}
