"use client";
import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,ArrowDown,ArrowRight,ArrowUp,BarChart3,Check,Clock3,Edit3,Eye,EyeOff,ImagePlus,LayoutDashboard,LogOut,Palette,Plus,RefreshCw,Settings,ShieldCheck,Trophy,Trash2,Users,Vote,X,Zap} from 'lucide-react';
import {supabase} from '../lib/supabase';

const FALLBACK={project_name:'CYBERSTAT',tagline:'CYBERSTAT FINAL BOSQICHI',hero_description:'Yakuniy bosqichda o‘zingiz munosib deb bilgan finalistga ovoz bering.',site_badge:'FINAL EVENT',footer_left:'CYBERSTAT FINAL ARENA',footer_right:'SECURE • CENTRAL • REAL-TIME',status:'FAOL',results_visible:true,countdown_end:null};
const fmt=n=>new Intl.NumberFormat('uz-UZ').format(Number(n||0));
const pct=(v,t)=>t?Number(v||0)/t*100:0;
const errText=e=>String(e?.message||e||'Noma’lum server xatosi').replace(/^.*?: /,'');
async function voterSession(){const {data,error}=await supabase.auth.getSession();if(error)throw error;if(data?.session?.user)return data.session;const r=await supabase.auth.signInAnonymously();if(r.error)throw r.error;if(!r.data?.session?.user)throw new Error('ANONYMOUS_AUTH_FAILED');return r.data.session;}
async function publicState(){const {data,error}=await supabase.rpc('get_public_state');if(error)throw error;return data||{candidates:[],settings:FALLBACK,participants:0};}
async function adminState(){const {data,error}=await supabase.rpc('admin_get_state');if(error)throw error;return data;}

export default function CyberStatApp(){const [mode,setMode]=useState(typeof window!=='undefined'&&window.location.pathname.startsWith('/admin')?'admin':'public');return mode==='admin'?<AdminApp onPublic={()=>{history.pushState({},'', '/');setMode('public')}}/>:<PublicApp onAdmin={()=>{history.pushState({},'', '/admin');setMode('admin')}}/>}

function PublicApp({onAdmin}){
 const [data,setData]=useState({candidates:[],settings:FALLBACK,participants:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[voteOpen,setVoteOpen]=useState(false),[voted,setVoted]=useState(false),[notice,setNotice]=useState(''),[syncAt,setSyncAt]=useState(null);
 const sync=useCallback(async()=>{try{const d=await publicState();setData(d);setSyncAt(new Date());setError('')}catch(e){console.error(e);setError(errText(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{sync();const ch=supabase.channel('cyberstat-public-live').on('postgres_changes',{event:'*',schema:'public',table:'candidates'},sync).on('postgres_changes',{event:'*',schema:'public',table:'survey_settings'},sync).on('postgres_changes',{event:'*',schema:'public',table:'survey_stats'},sync).subscribe();return()=>supabase.removeChannel(ch)},[sync]);
 const total=useMemo(()=>data.candidates.reduce((a,c)=>a+Number(c.votes||0),0),[data.candidates]);
 const openVoting=()=>setVoteOpen(true);
 const vote=async()=>{if(!selected||voted||data.settings.status!=='FAOL')return;try{await voterSession();const {data:r,error:e}=await supabase.rpc('cast_vote',{p_candidate_id:selected.id});if(e)throw e;if(!r?.ok)throw new Error('VOTE_NOT_CONFIRMED');setVoted(true);setSelected(null);setNotice('Ovozingiz muvaffaqiyatli qayd etildi.');await sync()}catch(e){setNotice(String(e?.message||'').includes('ALREADY_VOTED')?'Siz avval ovoz bergansiz.':'Ovoz qabul qilinmadi: '+errText(e))}};
 if(loading)return <Loading/>; const s=data.settings||FALLBACK,closed=s.status==='YAKUNLANGAN',visible=s.results_visible!==false;
 return <div className="app"><CyberBg/><header className="nav"><div className="logo"><span><ShieldCheck/></span><b>{s.project_name||'CYBERSTAT'}</b><small>FINAL ARENA</small></div><div className="nav-live"><i/> {closed?'FINAL CLOSED':'LIVE ARENA'}</div><nav><a href="#arena">ARENA</a><a href="#finalists">FINALISTLAR</a>{visible&&<a href="#ranking">REYTING</a>}</nav><button className="nav-btn" onClick={openVoting}><Vote/> OVOZ BERISH</button></header>
 {error&&<div className="alert error"><span>{error}</span><button onClick={sync}><RefreshCw/> QAYTA URINISH</button></div>}{notice&&<div className="alert success"><Check/><span>{notice}</span><button onClick={()=>setNotice('')}><X/></button></div>}
 <main><section id="arena" className="arena"><div className="arena-copy"><div className="kicker"><span>● {s.site_badge||'FINAL EVENT'}</span><em>{closed?'FINAL YAKUNLANDI':s.status==='TOXTATILGAN'?'VAQTINCHA TO‘XTATILGAN':'LIVE VOTING'}</em></div><h1>{s.project_name||'CYBERSTAT'}<br/><strong>FINAL BOSQICHI</strong></h1><p>{s.hero_description||'Yakuniy bosqichda o‘zingiz munosib deb bilgan finalistga ovoz bering.'}</p><div className="hero-actions"><button className="primary" disabled={s.status!=='FAOL'} onClick={openVoting}><Zap/> {closed?'FINAL YAKUNLANGAN':s.status==='TOXTATILGAN'?'OVOZ BERISH TO‘XTATILGAN':'OVOZ BERISH'} <ArrowRight/></button><span className="sync-label"><i/> SERVER {syncAt?'SINXRON':'ULANISH'}</span></div></div><ArenaPanel candidates={data.candidates} total={total} settings={s}/></section>
 <section className="metrics"><Metric label="JAMI OVOZ" value={total}/><Metric label="ISHTIROKCHI" value={data.participants}/><Metric label="FINALIST" value={data.candidates.length}/><Metric label="HOLAT" value={closed?'CLOSED':s.status==='TOXTATILGAN'?'PAUSE':'LIVE'}/></section>
 <section id="finalists" className="section"><SectionHead eyebrow={`FINALISTS / ${String(data.candidates.length).padStart(2,'0')}`} title="Finalistlar" text="Har bir loyiha uchun muallif, logo, tavsif, reyting va joriy ovozlar."/><div className="cards">{data.candidates.map((c,i)=><Candidate key={c.id} c={c} rank={i+1} total={total} disabled={voted||s.status!=='FAOL'} select={()=>setSelected(c)}/>)}</div></section>
 {visible&&<section id="ranking" className="ranking section"><SectionHead eyebrow="LIVE RANKING" title="Jonli reyting" text="Markaziy serverdagi joriy ovozlar asosida."/><div className="rank-list">{data.candidates.map((c,i)=><RankRow key={c.id} c={c} rank={i+1} total={total}/>)}</div></section>}
 {closed&&<Podium candidates={data.candidates}/>}<div className="public-note">{s.public_notice||'Ommaga faqat finalistlarning loyiha ma’lumotlari, reytingi, ovozlari va joriy o‘rni ko‘rsatiladi.'}</div></main>
 {voteOpen&&<VotingMenu candidates={data.candidates} status={s.status} voted={voted} onClose={()=>setVoteOpen(false)} onSelect={c=>{setSelected(c);setVoteOpen(false)}}/>}
 <footer><span>{s.footer_left||'CYBERSTAT FINAL ARENA'}</span><span>{s.footer_right||'SECURE • CENTRAL • REAL-TIME'}</span><button className="admin-link" onClick={onAdmin}>ADMIN</button></footer>{selected&&<Confirm c={selected} onClose={()=>setSelected(null)} onConfirm={vote}/>}</div>
}
function VotingMenu({candidates,status,voted,onClose,onSelect}){const closed=status!=='FAOL';return <div className="vote-menu-bg"><div className="vote-menu"><header><div><small>CYBERSTAT / SECURE BALLOT</small><h2>Finalistni tanlang</h2><p>Ovoz berish uchun quyidagi finalistlardan birini tanlang.</p></div><button onClick={onClose}><X/></button></header>{closed&&<div className="vote-menu-status">{status==='YAKUNLANGAN'?'Ovoz berish yakunlangan.':'Ovoz berish vaqtincha to‘xtatilgan.'}</div>}{voted&&<div className="vote-menu-status">Sizning ovozingiz allaqachon qayd etilgan.</div>}<div className="vote-menu-grid">{candidates.map((c,i)=><button className="vote-choice" key={c.id} onClick={()=>!closed&&!voted&&onSelect(c)} disabled={closed||voted}><div className="vote-menu-photo">{c.image_url?<img src={c.image_url} alt={c.author_name||c.name}/>:<div><ShieldCheck/></div>}<span>#{String(i+1).padStart(2,'0')}</span></div><div className="vote-choice-info"><small>{c.author_name||'Muallif'}</small><strong>{c.name}</strong><em>★ {Number(c.rating||0).toFixed(1)} / 5.0</em></div><ArrowRight/></button>)}</div><div className="vote-menu-footer"><span>1 QURILMA = 1 OVOZ</span><span>SECURE • CENTRAL • REAL-TIME</span></div></div></div>}
function ArenaPanel({candidates,total,settings}){const leader=candidates[0],end=settings.countdown_end?new Date(settings.countdown_end):null;return <div className="arena-panel"><div className="panel-top"><span><i/> LIVE ARENA</span><Countdown end={end} closed={settings.status==='YAKUNLANGAN'}/></div><div className="radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-core"><Trophy/><b>{leader?'#01':'—'}</b><small>LEADER</small></div></div>{leader?<div className="panel-leader"><small>HOZIRGI YETAKCHI</small><strong>{leader.name}</strong><span>{fmt(leader.votes)} OVOZ • {pct(leader.votes,total).toFixed(1)}%</span></div>:<div className="empty">Finalistlar hali kiritilmagan.</div>}</div>}
function Countdown({end,closed}){const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);if(closed)return <b className="closed-tag">CLOSED</b>;if(!end)return <b className="countdown">FINAL LIVE</b>;const s=Math.max(0,Math.floor((end-now)/1000)),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;return <b className="countdown"><Clock3/> {d?`${d}K `:''}{String(h).padStart(2,'0')}:{String(m).padStart(2,'0')}:{String(sec).padStart(2,'0')}</b>}
function Candidate({c,rank,total,disabled,select}){return <article className="candidate"><div className="photo">{c.image_url?<img src={c.image_url} alt={c.author_name||c.name}/>:<div><ShieldCheck/></div>}<span>#{String(rank).padStart(2,'0')}</span><div className="author-chip"><small>LOYIHA MUALLIFI</small><strong>{c.author_name||'Muallif'}</strong></div></div><div className="cbody"><div className="project-head">{c.project_logo_url?<img className="project-logo" src={c.project_logo_url} alt="Loyiha logosi"/>:<div className="project-logo placeholder"><ShieldCheck/></div>}<div><div className="cmeta"><span>FINALIST / LOYIHA</span><b>★ {Number(c.rating||0).toFixed(1)}/5.0</b></div><h3>{c.name}</h3></div></div><p className="project-desc">{c.bio||'Loyiha haqida ma’lumot kiritilmagan.'}</p><div className="vote-line"><strong>{fmt(c.votes)}</strong><span>OVOZ</span><em>{pct(c.votes,total).toFixed(1)}%</em></div><div className="bar"><i style={{width:`${Math.min(100,pct(c.votes,total))}%`}}/></div><button onClick={select} disabled={disabled}><Vote/> OVOZ BERISH <ArrowRight/></button></div></article>}
function RankRow({c,rank,total}){return <div className="rank-row"><b className="rank-no">{String(rank).padStart(2,'0')}</b>{c.image_url?<img src={c.image_url} alt=""/>:<span className="rank-avatar"><ShieldCheck/></span>}<div><strong>{c.name}</strong><small>★ {Number(c.rating||0).toFixed(1)} / 5.0</small></div><div className="rank-progress"><i style={{width:`${Math.min(100,pct(c.votes,total))}%`}}/></div><b className="rank-votes">{fmt(c.votes)} <small>OVOZ</small></b></div>}
function Podium({candidates}){return <section className="podium section"><div className="kicker"><span>FINAL RESULT</span><em>OFFICIAL</em></div><h2>Final natijasi</h2><div className="podium-grid">{candidates.slice(0,3).map((c,i)=><div className={`pod p${i+1}`} key={c.id}><span>#{i+1}</span><Trophy/><strong>{c.name}</strong><b>{fmt(c.votes)} ovoz</b></div>)}</div></section>}
function Confirm({c,onClose,onConfirm}){return <div className="modal-bg"><div className="modal"><button onClick={onClose}><X/></button><small>SECURE BALLOT</small><h2>{c.name}</h2><div className="confirm-rating">★ {Number(c.rating||0).toFixed(1)} / 5.0</div><p>Bu finalistga bitta ovoz berishni tasdiqlaysiz. Ovoz serverda qayd etiladi.</p><div><button className="secondary" onClick={onClose}>BEKOR</button><button className="primary" onClick={onConfirm}><Check/> TASDIQLASH</button></div></div></div>}
function Metric({label,value}){return <div><small>{label}</small><b>{typeof value==='number'?fmt(value):value}</b></div>}
function SectionHead({eyebrow,title,text}){return <div className="section-head"><div><small>{eyebrow}</small><h2>{title}</h2><p>{text}</p></div></div>}
function Loading(){return <div className="loading"><ShieldCheck/><b>CYBERSTAT</b><span>FINAL ARENA INITIALIZING…</span></div>}
function CyberBg(){return <div className="bg"><div className="grid"/><div className="glow g1"/><div className="glow g2"/></div>}

function AdminApp({onPublic}){
 const [session,setSession]=useState(null),[login,setLogin]=useState({email:'',password:''}),[state,setState]=useState(null),[analytics,setAnalytics]=useState(null),[tab,setTab]=useState('dashboard'),[edit,setEdit]=useState(null),[adjust,setAdjust]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=useCallback(async()=>{try{const [s,a]=await Promise.all([adminState(),supabase.rpc('admin_get_analytics').then(x=>{if(x.error)throw x.error;return x.data})]);setState(s);setAnalytics(a)}catch(e){setMsg(errText(e))}},[]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session))},[]);useEffect(()=>{if(session)load()},[session,load]);
 async function signIn(e){e.preventDefault();setBusy(true);setMsg('');const {data,error}=await supabase.auth.signInWithPassword(login);setBusy(false);if(error)setMsg(errText(error));else setSession(data.session)}
 if(!session)return <div className="admin-login"><CyberBg/><div className="login-card"><span className="admin-mark"><ShieldCheck/></span><small>CYBERSTAT / CONTROL CENTER</small><h1>Admin panel</h1><p>Saytning markaziy boshqaruv tizimi.</p><form onSubmit={signIn}><input type="email" placeholder="Email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input type="password" placeholder="Parol" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="primary" disabled={busy}>{busy?'KIRILMOQDA…':'KIRISH'} <ArrowRight/></button></form>{msg&&<div className="form-error">{msg}</div>}<button className="back-public" onClick={onPublic}>← Public sahifaga qaytish</button></div></div>;
 const cands=state?.candidates||[],settings=state?.settings||FALLBACK,total=cands.reduce((a,c)=>a+Number(c.votes||0),0);
 async function saveCandidate(c){setBusy(true);try{const upload=async(file,prefix,existing)=>{if(!file)return existing||null;if(file.size>5*1024*1024)throw new Error('Rasm 5 MB dan oshmasin.');const ext=file.name.split('.').pop().toLowerCase();if(!['png','jpg','jpeg','webp'].includes(ext))throw new Error('Faqat PNG/JPG/WEBP.');const path=`${prefix}/${c.id||crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from('candidate-images').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(up.error)throw up.error;return supabase.storage.from('candidate-images').getPublicUrl(path).data.publicUrl};const image=await upload(c.author_file,'authors',c.image_url);const logo=await upload(c.logo_file,'logos',c.project_logo_url);const r=await supabase.rpc('admin_save_candidate',{p_id:c.id||null,p_name:c.name,p_bio:c.bio||'',p_active:!!c.active,p_image_url:image,p_rating:Number(c.rating||5),p_author_name:c.author_name||'',p_project_logo_url:logo});if(r.error)throw r.error;setEdit(null);setMsg('Finalist ma’lumotlari serverga saqlandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
 async function adjustVotes(){setBusy(true);try{const r=await supabase.rpc('admin_adjust_votes',{p_candidate_id:adjust.id,p_delta:Number(adjust.delta),p_reason:adjust.reason});if(r.error)throw r.error;setAdjust(null);setMsg('Ovozlar markaziy serverda yangilandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
 async function remove(id){if(!confirm('Nomzodni o‘chirish/faolsizlantirishni tasdiqlaysizmi?'))return;setBusy(true);try{const r=await supabase.rpc('admin_delete_candidate',{p_candidate_id:id});if(r.error)throw r.error;setMsg('Nomzod holati yangilandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
 async function saveSettings(draft){setBusy(true);try{const r=await supabase.rpc('admin_set_settings',{p_status:draft.status,p_results_visible:draft.results_visible,p_countdown_end:draft.countdown_end||null});if(r.error)throw r.error;const c=await supabase.rpc('admin_set_content',{p_project_name:draft.project_name,p_tagline:draft.tagline,p_hero_description:draft.hero_description,p_site_badge:draft.site_badge,p_public_notice:draft.public_notice,p_footer_left:draft.footer_left,p_footer_right:draft.footer_right});if(c.error)throw c.error;setMsg('Sayt sozlamalari markaziy serverda saqlandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}
 async function logout(){await supabase.auth.signOut();setSession(null);onPublic()}
 const tabs=[['dashboard','Dashboard',LayoutDashboard],['candidates','Finalistlar',Users],['rating','Reyting',Trophy],['votes','Ovoz boshqaruvi',Vote],['analytics','Analitika',BarChart3],['content','Sayt kontenti',Palette],['system','Final boshqaruvi',Settings],['logs','Audit log',Activity]];
 return <div className="admin-shell"><CyberBg/><header className="admin-top"><div className="logo"><span><ShieldCheck/></span><b>CYBERSTAT</b><small>CONTROL CENTER</small></div><div className="admin-actions"><button onClick={onPublic}><Eye/> PUBLIC</button><button onClick={logout}><LogOut/> CHIQISH</button></div></header><div className="admin-layout"><aside>{tabs.map(([id,t,I])=><button key={id} className={tab===id?'sel':''} onClick={()=>setTab(id)}><I/> {t}</button>)}</aside><main className="admin-main">{msg&&<div className="admin-msg">{msg}<button onClick={()=>setMsg('')}><X/></button></div>}
 {tab==='dashboard'&&<AdminDashboard cands={cands} total={total} participants={state?.participants||0} settings={settings} analytics={analytics}/>} {tab==='candidates'&&<AdminCandidates cands={cands} onEdit={setEdit} onNew={()=>setEdit({id:null,name:'',bio:'',author_name:'',active:true,rating:5,image_url:'',project_logo_url:'',author_file:null,logo_file:null})} onDelete={remove}/>} {tab==='rating'&&<AdminRating cands={cands} busy={busy} onSave={async(id,rating)=>{setBusy(true);try{const r=await supabase.rpc('admin_set_rating',{p_candidate_id:id,p_rating:Number(rating)});if(r.error)throw r.error;setMsg('Reyting markaziy serverda saqlandi.');await load()}catch(e){setMsg(errText(e))}finally{setBusy(false)}}}/>} {tab==='votes'&&<AdminVotes cands={cands} onAdjust={setAdjust}/>} {tab==='analytics'&&<AdminAnalytics data={analytics} cands={cands}/>} {tab==='content'&&<AdminContent settings={settings} busy={busy} onSave={saveSettings}/>} {tab==='system'&&<AdminSystem settings={settings} busy={busy} onSave={saveSettings}/>} {tab==='logs'&&<AdminLogs logs={state?.logs||[]}/>}</main></div>{edit&&<CandidateEditor c={edit} setC={setEdit} onClose={()=>setEdit(null)} onSave={saveCandidate} busy={busy}/>} {adjust&&<AdjustModal a={adjust} setA={setAdjust} onClose={()=>setAdjust(null)} onSave={adjustVotes} busy={busy}/>}</div>
}
function AdminDashboard({cands,total,participants,settings,analytics}){const leader=cands[0];return <div><AdminTitle eyebrow="COMMAND CENTER" title="To‘liq sayt boshqaruvi" text="Markaziy ovozlar, finalistlar, kontent va final holatini bitta paneldan boshqaring."/><div className="dash-cards"><Metric label="JAMI OVOZ" value={total}/><Metric label="ISHTIROKCHI" value={participants}/><Metric label="FINALIST" value={cands.length}/><Metric label="STATUS" value={settings.status}/></div><div className="dashboard-grid"><div className="admin-panel"><div className="panel-title"><h3>Jonli reyting</h3><span>REAL-TIME</span></div>{cands.map((c,i)=><RankRow key={c.id} c={c} rank={i+1} total={total}/>)}</div><div className="admin-panel command-card"><small>CURRENT LEADER</small><Trophy/><b>{leader?.name||'—'}</b><span>{leader?`${fmt(leader.votes)} OVOZ`: 'Finalist yo‘q'}</span><hr/><small>COUNTDOWN</small><strong>{settings.countdown_end?new Date(settings.countdown_end).toLocaleString('uz-UZ'):'Belgilanmagan'}</strong></div></div><div className="quick-grid"><div><b>CONTENT CONTROL</b><span>Public sahifa matnlarini boshqaring</span></div><div><b>VOTE CONTROL</b><span>Ovozlarni server orqali boshqaring</span></div><div><b>AUDIT TRAIL</b><span>Barcha admin o‘zgarishlari qayd etiladi</span></div></div></div>}
function AdminCandidates({cands,onEdit,onNew,onDelete}){return <div><AdminTitle eyebrow="CANDIDATE MANAGEMENT" title="Finalistlar" text="Rasm, logo, muallif, tavsif, reyting, active holat va o‘chirishni boshqaring."/><button className="primary add" onClick={onNew}><Plus/> YANGI FINALIST</button><div className="admin-table">{cands.map((c,i)=><div className="admin-candidate" key={c.id}>{c.image_url?<img src={c.image_url} alt=""/>:<span><ShieldCheck/></span>}<div><b>#{String(i+1).padStart(2,'0')} {c.name}</b><small>{c.author_name||'Muallif ko‘rsatilmagan'} • ★ {Number(c.rating||0).toFixed(1)} • {fmt(c.votes)} ovoz • {c.active?'FAOL':'YOPIQ'}</small></div>{c.project_logo_url&&<img className="admin-logo-thumb" src={c.project_logo_url} alt=""/>}<button onClick={()=>onEdit({...c,author_file:null,logo_file:null})}><Edit3/></button><button onClick={()=>onDelete(c.id)}><Trash2/></button></div>)}</div></div>}
function AdminRating({cands,busy,onSave}){const [draft,setDraft]=useState({});useEffect(()=>{const next={};cands.forEach(c=>{next[c.id]=Number(c.rating||0)});setDraft(next)},[cands]);return <div><AdminTitle eyebrow="RATING CONTROL" title="Reyting" text="Finalist reytinglarini ovozlardan mustaqil ravishda markaziy serverda boshqaring."/><div className="admin-table rating-table">{cands.map((c,i)=><div className="rating-admin-row" key={c.id}><div className="rating-person">{c.image_url?<img src={c.image_url} alt=""/>:<span><ShieldCheck/></span>}<div><b>#{String(i+1).padStart(2,'0')} {c.name}</b><small>{c.author_name||'Muallif ko‘rsatilmagan'}</small></div></div><div className="rating-control"><strong>★ {Number(draft[c.id]||0).toFixed(1)} / 5.0</strong><input type="range" min="0" max="5" step="0.1" value={draft[c.id]??0} onChange={e=>setDraft({...draft,[c.id]:Number(e.target.value)})}/></div><button className="primary" disabled={busy} onClick={()=>onSave(c.id,draft[c.id])}><Check/> SAQLASH</button></div>)}</div></div>}
function AdminVotes({cands,onAdjust}){return <div><AdminTitle eyebrow="VOTE CONTROL" title="Ovoz boshqaruvi" text="Istalgan miqdorni qo‘shing yoki ayiring. Sabab majburiy va auditga yoziladi."/><div className="admin-table">{cands.map(c=><div className="vote-admin-row" key={c.id}><div><b>{c.name}</b><small>{fmt(c.votes)} OVOZ</small></div><button className="plus" onClick={()=>onAdjust({id:c.id,name:c.name,delta:1,reason:''})}><ArrowUp/> QO‘SHISH</button><button className="minus" onClick={()=>onAdjust({id:c.id,name:c.name,delta:-1,reason:''})}><ArrowDown/> AYIRISH</button></div>)}</div></div>}
function AdminAnalytics({data,cands}){return <div><AdminTitle eyebrow="ANALYTICS" title="Ovoz analitikasi" text="Admin uchun batafsil statistika. Bu ma’lumotlar public saytga chiqarilmaydi."/><div className="dash-cards"><Metric label="JAMI OVOZ" value={data?.total_votes||0}/><Metric label="ISHTIROKCHI" value={data?.participants||0}/><Metric label="O‘RTACHA OVOZ" value={Math.round(data?.average_votes||0)}/><Metric label="ENG KATTA O‘SISH" value={data?.top_delta||0}/></div><div className="admin-panel"><div className="panel-title"><h3>Finalistlar bo‘yicha ulush</h3><span>PRIVATE</span></div>{cands.map((c,i)=>{const total=data?.total_votes||0;return <div className="analytics-row" key={c.id}><div><b>#{i+1} {c.name}</b><span>{fmt(c.votes)} ovoz</span></div><strong>{pct(c.votes,total).toFixed(1)}%</strong><div className="bar"><i style={{width:`${Math.min(100,pct(c.votes,total))}%`}}/></div></div>})}</div><div className="admin-panel"><div className="panel-title"><h3>Oxirgi kunlar</h3><span>14 KUN</span></div><div className="daily-grid">{(data?.daily||[]).map(d=><div key={d.day}><b>{fmt(d.votes)}</b><span>{d.day}</span></div>)}</div></div></div>}
function AdminContent({settings,busy,onSave}){const [d,setD]=useState(settings);useEffect(()=>setD(settings),[settings]);return <div><AdminTitle eyebrow="PUBLIC CONTENT CONTROL" title="Sayt kontenti" text="Asosiy saytda ko‘rinadigan matnlarni kodga kirmasdan boshqaring."/><div className="content-form"><label>Platforma nomi<input value={d.project_name||''} onChange={e=>setD({...d,project_name:e.target.value})}/></label><label>Final sarlavhasi<input value={d.tagline||''} onChange={e=>setD({...d,tagline:e.target.value})}/></label><label>Hero tavsifi<textarea value={d.hero_description||''} onChange={e=>setD({...d,hero_description:e.target.value})}/></label><label>Yuqori badge<input value={d.site_badge||''} onChange={e=>setD({...d,site_badge:e.target.value})}/></label><label>Public izoh<textarea value={d.public_notice||''} onChange={e=>setD({...d,public_notice:e.target.value})}/></label><div className="two"><label>Footer chap<input value={d.footer_left||''} onChange={e=>setD({...d,footer_left:e.target.value})}/></label><label>Footer o‘ng<input value={d.footer_right||''} onChange={e=>setD({...d,footer_right:e.target.value})}/></label></div><button className="primary" disabled={busy} onClick={()=>onSave(d)}><Check/> KONTENTNI SAQLASH</button></div></div>}
function AdminSystem({settings,busy,onSave}){const [d,setD]=useState(settings);useEffect(()=>setD(settings),[settings]);return <div><AdminTitle eyebrow="FINAL CONTROL" title="Final boshqaruvi" text="Ovoz berishni oching, to‘xtating yoki yakunlang. Natijalar va countdownni ham shu yerdan boshqaring."/><div className="system-panel"><label>Holat<select value={d.status} onChange={e=>setD({...d,status:e.target.value})}><option>FAOL</option><option>TOXTATILGAN</option><option>YAKUNLANGAN</option></select></label><label>Natijalarni ommaga ko‘rsatish<select value={d.results_visible?'true':'false'} onChange={e=>setD({...d,results_visible:e.target.value==='true'})}><option value="true">Ha</option><option value="false">Yo‘q</option></select></label><label>Countdown tugash vaqti<input type="datetime-local" value={d.countdown_end?new Date(d.countdown_end).toISOString().slice(0,16):''} onChange={e=>setD({...d,countdown_end:e.target.value?new Date(e.target.value).toISOString():null})}/></label><div className="status-grid"><div><b>FAOL</b><span>Ovoz qabul qilinadi</span></div><div><b>TOXTATILGAN</b><span>Vaqtincha ovoz yopiladi</span></div><div><b>YAKUNLANGAN</b><span>Podium ko‘rsatiladi</span></div></div><button className="primary" disabled={busy} onClick={()=>onSave(d)}>FINAL SOZLAMALARINI SAQLASH</button></div></div>}
function AdminLogs({logs}){return <div><AdminTitle eyebrow="AUDIT TRAIL" title="O‘zgarishlar tarixi" text="Bu ma’lumotlar faqat administrator uchun ko‘rinadi."/><div className="logs">{logs.map(l=><div key={l.id}><span>{new Date(l.created_at).toLocaleString('uz-UZ')}</span><b>{l.action}</b><strong>{l.target||'—'}</strong><p>{l.detail||''}</p></div>)}</div></div>}
function AdminTitle({eyebrow,title,text}){return <div className="admin-title"><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>}
function CandidateEditor({c,setC,onClose,onSave,busy}){return <div className="modal-bg"><div className="modal editor"><button onClick={onClose}><X/></button><small>FINALIST CONFIG / MEDIA</small><h2>{c.id?'Finalistni tahrirlash':'Yangi finalist'}</h2><input placeholder="Loyiha nomi" value={c.name} onChange={e=>setC({...c,name:e.target.value})}/><input placeholder="Loyiha muallifi" value={c.author_name||''} onChange={e=>setC({...c,author_name:e.target.value})}/><textarea placeholder="Loyiha tavsifi" value={c.bio} onChange={e=>setC({...c,bio:e.target.value})}/><label>Reyting: {Number(c.rating||0).toFixed(1)} / 5.0<input type="range" min="0" max="5" step="0.1" value={c.rating||0} onChange={e=>setC({...c,rating:e.target.value})}/></label><div className="media-grid"><label className="file-box"><ImagePlus/><span>Muallif rasmi</span><small>{c.author_file?c.author_file.name:(c.image_url?'Mavjud rasmni saqlash':'Rasm tanlang')}</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setC({...c,author_file:e.target.files?.[0]||null})}/></label><label className="file-box"><ImagePlus/><span>Loyiha logosi</span><small>{c.logo_file?c.logo_file.name:(c.project_logo_url?'Mavjud logo saqlanadi':'Logo tanlang')}</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setC({...c,logo_file:e.target.files?.[0]||null})}/></label></div>{(c.author_file||c.image_url)&&<div className="editor-preview"><div>{c.author_file?<span>{c.author_file.name}</span>:<img src={c.image_url} alt=""/>}<small>MUALLIF</small></div>{(c.logo_file||c.project_logo_url)&&<div>{c.logo_file?<span>{c.logo_file.name}</span>:<img src={c.project_logo_url} alt=""/>}<small>LOGO</small></div>}</div>}<label className="switch"><input type="checkbox" checked={!!c.active} onChange={e=>setC({...c,active:e.target.checked})}/> FAOL</label><div><button className="secondary" onClick={onClose}>BEKOR</button><button className="primary" disabled={busy} onClick={()=>onSave(c)}><Check/> SAQLASH</button></div></div></div>}
function AdjustModal({a,setA,onClose,onSave,busy}){return <div className="modal-bg"><div className="modal"><button onClick={onClose}><X/></button><small>SECURE VOTE ADJUSTMENT</small><h2>{a.name}</h2><div className="adjust-grid"><button onClick={()=>setA({...a,delta:Number(a.delta||0)+1})}>+1</button><button onClick={()=>setA({...a,delta:Number(a.delta||0)-1})}>−1</button><input type="number" value={a.delta} onChange={e=>setA({...a,delta:e.target.value})}/></div><textarea placeholder="O‘zgarish sababi — majburiy" value={a.reason} onChange={e=>setA({...a,reason:e.target.value})}/><p className="warning">Sabab audit logga yoziladi. O‘zgarish public reytingga real vaqtda tarqaladi.</p><div><button className="secondary" onClick={onClose}>BEKOR</button><button className="primary" disabled={busy} onClick={onSave}><Check/> TASDIQLASH</button></div></div></div>}
